openapi: 3.0.3
info:
  title: Compliance Service API Specification
  version: '95'
  description: API documentation for the Compliance Service bounded context.
servers:
  - url: /api/v1
    description: Development Server
tags:
  - name: ComplianceService
    description: Operations related to the ComplianceService bounded context.
paths:
  /adopt-regulation:
    post:
      summary: Adopt Regulation
      description: Executes the "Adopt Regulation" command. ...
      operationId: adoptRegulation
      tags:
        - ComplianceService
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Regulation'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdoptRegulationRequest'
  /define-policy:
    post:
      summary: Define Policy
      description: Executes the "Define Policy" command. ...
      operationId: definePolicy
      tags:
        - ComplianceService
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DefinePolicyRequest'
  /perform-monitoring-run:
    post:
      summary: Perform Monitoring Run
      description: Executes the "Perform Monitoring Run" command. ...
      operationId: performMonitoringRun
      tags:
        - ComplianceService
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitoringRun'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerformMonitoringRunRequest'
  /detect-non-compliance:
    post:
      summary: Detect Non-Compliance
      description: Executes the "Detect Non-Compliance" command. ...
      operationId: detectNonCompliance
      tags:
        - ComplianceService
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Non-ComplianceCase'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectNon-ComplianceRequest'
  /review-non-compliance-case:
    post:
      summary: Review Non-Compliance Case
      description: Executes the "Review Non-Compliance Case" command. ...
      operationId: reviewNonComplianceCase
      tags:
        - ComplianceService
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Non-ComplianceCase'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewNon-ComplianceCaseRequest'
  /get-all-regulations:
    get:
      summary: Get All Regulations
      description: Retrieves data based on the "Get All Regulations" query. This is a synchronous query operation.
      operationId: getAllRegulations
      tags:
        - ComplianceService
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAllRegulationsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /get-all-policys:
    get:
      summary: Get All Policys
      description: Retrieves data based on the "Get All Policys" query. This is a synchronous query operation.
      operationId: getAllPolicys
      tags:
        - ComplianceService
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAllPolicysResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /get-all-monitoring-runs:
    get:
      summary: Get All Monitoring Runs
      description: Retrieves data based on the "Get All Monitoring Runs" query. This is a synchronous query operation.
      operationId: getAllMonitoringRuns
      tags:
        - ComplianceService
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAllMonitoringRunsResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /get-all-non-compliance-cases:
    get:
      summary: Get All Non-Compliance Cases
      description: Retrieves data based on the "Get All Non-Compliance Cases" query. This is a synchronous query operation.
      operationId: getAllNonComplianceCases
      tags:
        - ComplianceService
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAllNon-ComplianceCasesResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          example: An error occurred.
    Regulation:
      type: object
      description: Represents a Regulation in the system.
      properties:
        id:
          type: string
          description: Unique identifier for the Regulation (primary key).
          example: reg-001
        regulationTitle:
          type: string
          description: The regulationTitle of the Regulation.
          example: GDPR Compliance
        regulationNumber:
          type: string
          description: The regulationNumber of the Regulation.
          example: EU 2016/679
        issuingBody:
          type: string
          description: The issuingBody of the Regulation.
          example: European Parliament
        effectiveDate:
          type: string
          description: The effectiveDate of the Regulation.
          example: '2018-05-25'
        description:
          type: string
          description: The description of the Regulation.
          example: Data Protection Reg
      required:
        - id
        - regulationTitle
        - regulationNumber
        - issuingBody
        - effectiveDate
    Policy:
      type: object
      description: Represents a Policy in the system.
      properties:
        id:
          type: string
          description: Unique identifier for the Policy (primary key).
          example: pol-A01
        regulationId:
          type: string
          description: The regulationId of the Policy.
          example: reg-001
        policyTitle:
          type: string
          description: The policyTitle of the Policy.
          example: Data Access Policy
        policyDescription:
          type: string
          description: The policyDescription of the Policy.
          example: Defines data access rules
        effectiveDate:
          type: string
          description: The effectiveDate of the Policy.
          example: '2023-01-15'
        version:
          type: string
          description: The version of the Policy.
          example: '1.0'
      required:
        - id
        - regulationId
        - policyTitle
        - policyDescription
        - effectiveDate
        - version
    MonitoringRun:
      type: object
      description: Represents a Monitoring Run in the system.
      properties:
        id:
          type: string
          description: Unique identifier for the Monitoring Run (primary key).
          example: mrun-101
        monitoringConfigurationId:
          type: string
          description: The monitoringConfigurationId of the Monitoring Run.
          example: config-001
        monitoringScope:
          type: string
          description: The monitoringScope of the Monitoring Run.
          example: All Data
        runTimestamp:
          type: string
          description: The runTimestamp of the Monitoring Run.
          example: '2023-10-26T10:00:00Z'
        triggeredBy:
          type: string
          description: The triggeredBy of the Monitoring Run.
          example: Scheduler
      required:
        - id
        - monitoringConfigurationId
        - monitoringScope
        - runTimestamp
        - triggeredBy
    Non-ComplianceCase:
      type: object
      description: Represents a Non-Compliance Case in the system.
      properties:
        id:
          type: string
          description: Unique identifier for the Non-Compliance Case (primary key).
          example: ncc-001
        monitoringRunId:
          type: string
          description: The monitoringRunId of the Non-Compliance Case.
          example: mrun-101
        detectedPolicyId:
          type: string
          description: The detectedPolicyId of the Non-Compliance Case.
          example: pol-A01
        issueDescription:
          type: string
          description: The issueDescription of the Non-Compliance Case.
          example: Unauthorized data access
        detectedDate:
          type: string
          description: The detectedDate of the Non-Compliance Case.
          example: '2023-10-26'
        severity:
          type: string
          description: The severity of the Non-Compliance Case.
          example: High
        reviewOutcome:
          type: string
          description: The reviewOutcome of the Non-Compliance Case.
          example: Confirmed
        reviewerId:
          type: string
          description: The reviewerId of the Non-Compliance Case.
          example: user-CO-01
        reviewDate:
          type: string
          description: The reviewDate of the Non-Compliance Case.
          example: '2023-10-27'
        reviewComment:
          type: string
          description: The reviewComment of the Non-Compliance Case.
          example: Details verified
      required:
        - id
        - monitoringRunId
        - detectedPolicyId
        - issueDescription
        - detectedDate
        - severity
        - reviewOutcome
        - reviewerId
        - reviewDate
    AdoptRegulationRequest:
      type: object
      properties:
        regulationTitle:
          type: string
          example: GDPR Compliance
        regulationNumber:
          type: string
          example: EU 2016/679
        issuingBody:
          type: string
          example: European Parliament
        effectiveDate:
          type: string
          example: '2018-05-25'
      required:
        - regulationTitle
        - regulationNumber
        - issuingBody
        - effectiveDate
    DefinePolicyRequest:
      type: object
      properties:
        regulationId:
          type: string
          example: reg-001
        policyTitle:
          type: string
          example: Data Access Policy
        policyDescription:
          type: string
          example: Defines data access rules
        effectiveDate:
          type: string
          example: '2023-01-15'
        version:
          type: string
          example: '1.0'
      required:
        - regulationId
        - policyTitle
        - policyDescription
        - effectiveDate
        - version
    PerformMonitoringRunRequest:
      type: object
      properties:
        monitoringConfigurationId:
          type: string
          example: config-001
        monitoringScope:
          type: string
          example: All Data
        runTimestamp:
          type: string
          example: '2023-10-26T10:00:00Z'
        triggeredBy:
          type: string
          example: Scheduler
      required:
        - monitoringConfigurationId
        - monitoringScope
        - runTimestamp
        - triggeredBy
    DetectNon-ComplianceRequest:
      type: object
      properties:
        monitoringRunId:
          type: string
          example: mrun-101
        detectedPolicyId:
          type: string
          example: pol-A01
        issueDescription:
          type: string
          example: Unauthorized data access
        detectedDate:
          type: string
          example: '2023-10-26'
        severity:
          type: string
          example: High
      required:
        - monitoringRunId
        - detectedPolicyId
        - issueDescription
        - detectedDate
        - severity
    ReviewNon-ComplianceCaseRequest:
      type: object
      properties:
        id:
          type: string
          example: ncc-001
        reviewComment:
          type: string
          example: Details verified
        reviewOutcome:
          type: string
          example: Confirmed
        reviewerId:
          type: string
          example: user-CO-01
        reviewDate:
          type: string
          example: '2023-10-27'
      required:
        - id
        - reviewOutcome
        - reviewerId
        - reviewDate
    GetAllRegulationsResponse:
      type: object
      description: Response schema for the Get All Regulations query.
      properties:
        id:
          type: string
          description: The id of the Regulation.
          example: reg-001
        regulationTitle:
          type: string
          description: The regulationTitle of the Regulation.
          example: GDPR Compliance
        regulationNumber:
          type: string
          description: The regulationNumber of the Regulation.
          example: EU 2016/679
        issuingBody:
          type: string
          description: The issuingBody of the Regulation.
          example: European Parliament
        effectiveDate:
          type: string
          description: The effectiveDate of the Regulation.
          example: '2018-05-25'
        status:
          type: string
          description: The status of the Regulation.
    GetAllPolicysResponse:
      type: object
      description: Response schema for the Get All Policys query.
      properties:
        id:
          type: string
          description: The id of the Policy.
          example: pol-A01
        policyTitle:
          type: string
          description: The policyTitle of the Policy.
          example: Data Access Policy
        effectiveDate:
          type: string
          description: The effectiveDate of the Policy.
          example: '2023-01-15'
        monitoringConfigId:
          type: string
          description: The monitoringConfigId of the Policy.
        status:
          type: string
          description: The status of the Policy.
    GetAllMonitoringRunsResponse:
      type: object
      description: Response schema for the Get All Monitoring Runs query.
      properties:
        id:
          type: string
          description: The id of the Monitoring Run.
          example: mrun-101
        runTimestamp:
          type: string
          description: The runTimestamp of the Monitoring Run.
          example: '2023-10-26T10:00:00Z'
        monitoringScope:
          type: string
          description: The monitoringScope of the Monitoring Run.
          example: All Data
        status:
          type: string
          description: The status of the Monitoring Run.
        findingsSummary:
          type: string
          description: The findingsSummary of the Monitoring Run.
    GetAllNon-ComplianceCasesResponse:
      type: object
      description: Response schema for the Get All Non-Compliance Cases query.
      properties:
        id:
          type: string
          description: The id of the Non-Compliance Case.
          example: ncc-001
        issueDescription:
          type: string
          description: The issueDescription of the Non-Compliance Case.
          example: Unauthorized data access
        detectedDate:
          type: string
          description: The detectedDate of the Non-Compliance Case.
          example: '2023-10-26'
        severity:
          type: string
          description: The severity of the Non-Compliance Case.
          example: High
        detectedPolicyId:
          type: string
          description: The detectedPolicyId of the Non-Compliance Case.
          example: pol-A01
        status:
          type: string
          description: The status of the Non-Compliance Case.
  parameters:
    RegulationId:
      name: id
      in: path
      required: true
      description: The unique identifier for the Regulation.
      schema:
        type: string
    PolicyId:
      name: id
      in: path
      required: true
      description: The unique identifier for the Policy.
      schema:
        type: string
    MonitoringRunId:
      name: id
      in: path
      required: true
      description: The unique identifier for the Monitoring Run.
      schema:
        type: string
    Non-ComplianceCaseId:
      name: id
      in: path
      required: true
      description: The unique identifier for the Non-Compliance Case.
      schema:
        type: string
  responses:
    BadRequest:
      description: 'Bad Request: The server cannot or will not process the request due to something that is perceived to be a client error.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 'Not Found: The server can not find the requested resource.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: 'Internal Server Error: The server has encountered a situation it doesn''t know how to handle.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
